"""Fully update 006_claude-opus-4-8.ipynb — add vision_batch to all sections."""

import json
from pathlib import Path

p = Path("c:/Users/Nahid/dmpbridge/notebooks/006_claude-opus-4-8.ipynb")
nb = json.loads(p.read_bytes().lstrip(b"\xef\xbb\xbf"))
cells = nb["cells"]

# ── Cell 3 — Section 1 markdown ───────────────────────────────────────────────
cells[3]["source"] = (
    "## 1 — Accuracy summary\n\n"
    "- **Accuracy** = blocks where the predicted label exactly matches gold.\n"
    "- **Delta** = strategy accuracy minus batch. Positive = that strategy outperforms batch.\n"
    "- A single bad sample can pull the overall number down — check the per-sample view next.\n"
)

# ── Cell 4 — accuracy tables + delta comparison ───────────────────────────────
cells[4]["source"] = (
    "def print_table(df, label):\n"
    "    hdr = f\"{'Sample':<12}  {'Total':>5}  {'Correct':>7}  {'Errors':>6}  {'Accuracy':>8}  Formula\"\n"
    "    print(f\"  {label}\")\n"
    "    print(\"  \" + \"-\" * len(hdr))\n"
    "    for row in df.itertuples():\n"
    "        print(f\"  {row.sample:<12}  {row.total:>5}  {row.correct:>7}  \"\n"
    "              f\"{row.errors:>6}  {row.accuracy*100:>7.1f}%  {row.formula}\")\n"
    "    print(\"  \" + \"-\" * len(hdr))\n"
    "    tn, tc = df[\"total\"].sum(), df[\"correct\"].sum()\n"
    "    print(f\"  {'TOTAL':<12}  {tn:>5}  {tc:>7}  {tn-tc:>6}  {tc/tn*100:>7.1f}%  {tc}/{tn}\\n\")\n"
    "\n"
    "print_table(df_b, f\"Batch — {MODEL_NAME}\")\n"
    "if WHOLEDOC_AVAILABLE:\n"
    "    print_table(df_w, f\"Whole-doc — {MODEL_NAME}\")\n"
    "if PDF_AVAILABLE:\n"
    "    print_table(df_p, f\"PDF-direct — {MODEL_NAME}\")\n"
    "if VISION_AVAILABLE:\n"
    "    print_table(df_v, f\"Vision Batch — {MODEL_NAME}\")\n"
    "\n"
    "# ── Delta comparison across all available strategies ──────────────────────\n"
    "base = df_b[[\"sample\",\"accuracy\"]].rename(columns={\"accuracy\":\"batch\"})\n"
    "merged = base.copy()\n"
    "extra_cols = []\n"
    "if WHOLEDOC_AVAILABLE:\n"
    "    merged = merged.merge(df_w[[\"sample\",\"accuracy\"]].rename(columns={\"accuracy\":\"whole\"}), on=\"sample\")\n"
    "    extra_cols.append((\"whole\", \"Δ whole−batch\"))\n"
    "if PDF_AVAILABLE:\n"
    "    merged = merged.merge(df_p[[\"sample\",\"accuracy\"]].rename(columns={\"accuracy\":\"pdf\"}), on=\"sample\")\n"
    "    extra_cols.append((\"pdf\", \"Δ pdf−batch\"))\n"
    "if VISION_AVAILABLE:\n"
    "    merged = merged.merge(df_v[[\"sample\",\"accuracy\"]].rename(columns={\"accuracy\":\"vision\"}), on=\"sample\")\n"
    "    extra_cols.append((\"vision\", \"Δ vision−batch\"))\n"
    "\n"
    "for col, dcol in extra_cols:\n"
    "    merged[dcol] = merged[col] - merged[\"batch\"]\n"
    "\n"
    "all_strats = [\"batch\"] + [c for c, _ in extra_cols]\n"
    "all_dcols  = [d for _, d in extra_cols]\n"
    "header = \"  \" + f\"{'Sample':<12}\" + \"\".join(f\"  {s:>10}\" for s in all_strats) + \"\".join(f\"  {d:>16}\" for d in all_dcols)\n"
    "print(header)\n"
    "print(\"  \" + \"-\" * (len(header) - 2))\n"
    "for _, r in merged.iterrows():\n"
    "    row_str = f\"  {r['sample']:<12}\" + \"\".join(f\"  {r[s]*100:>9.1f}%\" for s in all_strats)\n"
    "    for d in all_dcols:\n"
    "        sign = '+' if r[d] >= 0 else ''\n"
    "        row_str += f\"  {sign}{r[d]*100:>14.1f}%\"\n"
    "    print(row_str)\n"
    "tb = df_b['correct'].sum() / df_b['total'].sum()\n"
    "ovr = f\"  {'OVERALL':<12}  {tb*100:>9.1f}%\"\n"
    "for col, dcol in extra_cols:\n"
    "    if col in merged.columns:\n"
    "        tc_ = merged[col].mean()\n"
    "        sign = '+' if (tc_ - merged['batch'].mean()) >= 0 else ''\n"
    "        ovr += f\"  {tc_*100:>9.1f}%\"\n"
    "print(\"  \" + \"-\" * (len(header) - 2))\n"
    "print(ovr)\n"
    "\n"
    "# ── Gold-matched precision ────────────────────────────────────────────────\n"
    "print(\"\\n\\n  ── Gold-matched precision (blocks that matched a manual-label item) ──\\n\")\n"
    "print(f\"  {'Strategy':<14}  {'Correct':>8}  {'Matched':>8}  {'All blocks':>11}  {'Gold prec':>10}  {'Block acc':>10}\")\n"
    "print(\"  \" + \"-\" * 68)\n"
    "avail = [(\"Batch\", conf_b, df_b), (\"Whole-doc\", conf_w, df_w) if WHOLEDOC_AVAILABLE else None,\n"
    "         (\"PDF-direct\", conf_p, df_p) if PDF_AVAILABLE else None,\n"
    "         (\"Vision Batch\", conf_v, df_v) if VISION_AVAILABLE else None]\n"
    "for item in avail:\n"
    "    if item is None: continue\n"
    "    strat_label, conf, df_strat = item\n"
    "    correct, covered, matched = gold_metrics(conf)\n"
    "    all_blocks = int(df_strat[\"total\"].sum())\n"
    "    gold_prec  = correct / matched    if matched    else 0\n"
    "    block_acc  = correct / all_blocks if all_blocks else 0\n"
    "    print(f\"  {strat_label:<14}  {correct:>8}  {matched:>8}  {all_blocks:>11}  {gold_prec*100:>9.1f}%  {block_acc*100:>9.1f}%\")\n"
)

# ── Cell 5 — Section 2 markdown ───────────────────────────────────────────────
cells[5]["source"] = (
    "## 2 — Per-sample accuracy\n\n"
    "Each cluster of bars = one sample. Strategies: Batch · Whole-doc · PDF-direct · Vision Batch.  \n"
    "Large gaps between strategies on the same sample highlight where input representation matters most.\n"
)

# ── Cell 6 — per-sample accuracy bar chart (4 strategies) ────────────────────
cells[6]["source"] = (
    "samples_ordered = df_b[\"sample\"].tolist()\n"
    "x = range(len(samples_ordered))\n"
    "\n"
    "active_strats = [\n"
    "    (\"Batch\",        df_b, COLOR_BATCH,  True),\n"
    "    (\"Whole-doc\",    df_w, COLOR_WHOLE,  WHOLEDOC_AVAILABLE),\n"
    "    (\"PDF-direct\",   df_p, COLOR_PDF,    PDF_AVAILABLE),\n"
    "    (\"Vision Batch\", df_v, COLOR_VISION, VISION_AVAILABLE),\n"
    "]\n"
    "active_strats = [(lbl, df, col) for lbl, df, col, flag in active_strats if flag]\n"
    "n_s = len(active_strats)\n"
    "w   = 0.8 / n_s\n"
    "\n"
    "fig, ax = plt.subplots(figsize=(14, 5))\n"
    "for i, (lbl, df, color) in enumerate(active_strats):\n"
    "    offset = (i - (n_s - 1) / 2) * w\n"
    "    acc = df.set_index(\"sample\").reindex(samples_ordered)[\"accuracy\"] * 100\n"
    "    bars = ax.bar([xi + offset for xi in x], acc, width=w,\n"
    "                  label=lbl, color=color, alpha=0.85, edgecolor=\"white\")\n"
    "    for bar, v in zip(bars, acc):\n"
    "        if not pd.isna(v):\n"
    "            ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.4,\n"
    "                    f\"{v:.0f}%\", ha=\"center\", va=\"bottom\", fontsize=7)\n"
    "    avg = acc.mean()\n"
    "    ax.axhline(avg, color=color, linestyle=\"--\", linewidth=0.9, alpha=0.6)\n"
    "\n"
    "ax.set_xticks(list(x)); ax.set_xticklabels(samples_ordered, rotation=30)\n"
    "ax.set_ylim(55, 118); ax.set_ylabel(\"Block-level accuracy (%)\")\n"
    "ax.set_title(f\"Per-sample accuracy — {MODEL_NAME} — all strategies\", pad=10)\n"
    "ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f\"{v:.0f}%\"))\n"
    "ax.legend(framealpha=0.9)\n"
    "sns.despine(); plt.tight_layout(); plt.show()\n"
)

# ── Cell 7 — Section 3 markdown ───────────────────────────────────────────────
cells[7]["source"] = (
    "## 3 — Confusion matrix\n\n"
    "Read **row by row**: each row = a true label, each column = what the model predicted.  \n"
    "A perfect model has all mass on the diagonal.  \n"
    "The most common failure mode is `question.text` being confused with `section.description` "
    "— both are funder-written text; the boundary is structural, not lexical.\n\n"
    "Shown for: Batch · Whole-doc · Vision Batch (PDF-direct has its own matrix in Section 6).\n"
)

# ── Cell 8 — confusion matrices (batch + whole-doc + vision) ──────────────────
cells[8]["source"] = (
    "def conf_to_df(conf):\n"
    "    m = pd.DataFrame(\n"
    "        [[conf.get(t, {}).get(p, 0) for p in LABELS] for t in LABELS],\n"
    "        index=SHORT, columns=SHORT)\n"
    "    return m, m.div(m.sum(axis=1).replace(0, 1), axis=0)\n"
    "\n"
    "mat_b, mat_bn = conf_to_df(conf_b)\n"
    "\n"
    "conf_panels = [(mat_b, mat_bn, CMAP_BATCH, \"Batch\")]\n"
    "if WHOLEDOC_AVAILABLE:\n"
    "    mat_w, mat_wn = conf_to_df(conf_w)\n"
    "    conf_panels.append((mat_w, mat_wn, CMAP_WHOLE, \"Whole-doc\"))\n"
    "if VISION_AVAILABLE:\n"
    "    mat_v2, mat_vn2 = conf_to_df(conf_v)\n"
    "    conf_panels.append((mat_v2, mat_vn2, CMAP_VISION, \"Vision Batch\"))\n"
    "\n"
    "n_rows = len(conf_panels)\n"
    "fig, axes = plt.subplots(n_rows, 2, figsize=(14, 5.5 * n_rows))\n"
    "if n_rows == 1:\n"
    "    axes = [axes]\n"
    "\n"
    "for row_i, (mat_raw, mat_norm, cmap, title) in enumerate(conf_panels):\n"
    "    for col_i, (mat, fmt, suffix) in enumerate([\n"
    "        (mat_raw,  \"d\",   \"raw counts\"),\n"
    "        (mat_norm, \".0%\", \"row-normalised recall\"),\n"
    "    ]):\n"
    "        ax = axes[row_i][col_i]\n"
    "        sns.heatmap(mat, annot=True, fmt=fmt, cmap=cmap, linewidths=0.6,\n"
    "                    linecolor=\"white\", ax=ax, cbar=False, annot_kws={\"size\": 11},\n"
    "                    vmin=(0 if fmt == \".0%\" else None), vmax=(1 if fmt == \".0%\" else None))\n"
    "        ax.set_title(f\"{title} — {suffix}\", pad=8, fontsize=11)\n"
    "        ax.set_xlabel(\"Predicted\", labelpad=6)\n"
    "        ax.set_ylabel(\"True\", labelpad=6)\n"
    "\n"
    "plt.suptitle(f\"Confusion matrices — {MODEL_NAME}\", fontsize=13, y=1.01)\n"
    "plt.tight_layout(); plt.show()\n"
)

# ── Cell 9 — Section 4 markdown ───────────────────────────────────────────────
cells[9]["source"] = (
    "## 4 — Precision / Recall / F1 per label\n\n"
    "F1 balances precision and recall. Values below 80% indicate a reliability risk.  \n"
    "The delta table shows per-label gain vs batch — the clearest signal for choosing a strategy.\n\n"
    "Shown for: Batch · Whole-doc · Vision Batch (PDF-direct F1 is in Section 6).\n"
)

# ── Cell 10 — F1 charts (batch + whole-doc + vision) ─────────────────────────
cells[10]["source"] = (
    "df_f1_b = compute_f1_rows(conf_b)\n"
    "\n"
    "f1_panels = [(df_f1_b, COLOR_BATCH, f\"Batch — {MODEL_NAME}\")]\n"
    "if WHOLEDOC_AVAILABLE:\n"
    "    df_f1_w = compute_f1_rows(conf_w)\n"
    "    f1_panels.append((df_f1_w, COLOR_WHOLE, f\"Whole-doc — {MODEL_NAME}\"))\n"
    "if VISION_AVAILABLE:\n"
    "    df_f1_v2 = compute_f1_rows(conf_v)\n"
    "    f1_panels.append((df_f1_v2, COLOR_VISION, f\"Vision Batch — {MODEL_NAME}\"))\n"
    "\n"
    "n_p = len(f1_panels)\n"
    "fig, axes = plt.subplots(1, n_p, figsize=(8 * n_p, 5))\n"
    "if n_p == 1: axes = [axes]\n"
    "\n"
    "for ax, (df_f1, color, title) in zip(axes, f1_panels):\n"
    "    xi, bw = range(len(LABELS)), 0.26\n"
    "    ax.bar([i - bw for i in xi], df_f1[\"precision\"]*100, width=bw,\n"
    "           label=\"Precision\", color=color, alpha=0.5, edgecolor=\"white\")\n"
    "    ax.bar([i      for i in xi], df_f1[\"recall\"]*100,    width=bw,\n"
    "           label=\"Recall\",    color=color, alpha=0.75, edgecolor=\"white\")\n"
    "    bars = ax.bar([i + bw for i in xi], df_f1[\"f1\"]*100, width=bw,\n"
    "                  label=\"F1\", color=color, edgecolor=\"white\")\n"
    "    for bar, row in zip(bars, df_f1.itertuples()):\n"
    "        ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.8,\n"
    "                f\"{row.f1*100:.0f}%\", ha=\"center\", va=\"bottom\",\n"
    "                fontsize=9, fontweight=\"bold\", color=color)\n"
    "    ax.set_xticks(list(xi)); ax.set_xticklabels(SHORT, fontsize=10)\n"
    "    ax.set_ylim(0, 120); ax.set_ylabel(\"Score (%)\"); ax.set_title(title, pad=10)\n"
    "    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f\"{v:.0f}%\"))\n"
    "    ax.legend(loc=\"upper right\", framealpha=0.9); sns.despine(ax=ax)\n"
    "\n"
    "plt.suptitle(f\"Precision / Recall / F1 — {MODEL_NAME}\", fontsize=13, y=1.02)\n"
    "plt.tight_layout(); plt.show()\n"
    "\n"
    "# ── Delta table vs batch ──────────────────────────────────────────────────\n"
    "delta_df = df_f1_b.set_index(\"label\")[[\"f1\"]].rename(columns={\"f1\":\"batch\"})\n"
    "if WHOLEDOC_AVAILABLE:\n"
    "    delta_df[\"whole-doc\"] = df_f1_w.set_index(\"label\")[\"f1\"].values\n"
    "    delta_df[\"Δ whole\"]   = delta_df[\"whole-doc\"] - delta_df[\"batch\"]\n"
    "if VISION_AVAILABLE:\n"
    "    delta_df[\"vision\"]    = df_f1_v2.set_index(\"label\")[\"f1\"].values\n"
    "    delta_df[\"Δ vision\"]  = delta_df[\"vision\"] - delta_df[\"batch\"]\n"
    "display(delta_df.style.format(\"{:.1%}\").background_gradient(\n"
    "    subset=[c for c in delta_df.columns if not c.startswith(\"Δ\")], cmap=\"Blues\"))\n"
)

# ── Cell 11 — Section 5 markdown ─────────────────────────────────────────────
cells[11]["source"] = (
    "## 5 — Mislabeled blocks\n\n"
    "Use this table to distinguish **systematic** errors (same true→pred pair, many blocks) "
    "from **isolated** ones.  \n"
    "Systematic patterns → prompt or strategy needs fixing. Isolated → acceptable noise.\n\n"
    "Shown for: Batch · Whole-doc · Vision Batch.\n"
)

# ── Cell 12 — error_breakdown calls ──────────────────────────────────────────
cells[12]["source"] = (
    "def error_breakdown(df_err, label):\n"
    "    print(f\"  {label}: {len(df_err)} mislabeled blocks\")\n"
    "    if df_err.empty:\n"
    "        print(\"  No errors.\\n\"); return\n"
    "    bd = (df_err.groupby([\"true\",\"pred\"]).size()\n"
    "          .reset_index(name=\"count\").sort_values(\"count\", ascending=False))\n"
    "    print(bd.to_string(index=False)); print()\n"
    "\n"
    "error_breakdown(errs_b, f\"Batch — {MODEL_NAME}\")\n"
    "if WHOLEDOC_AVAILABLE:\n"
    "    error_breakdown(errs_w, f\"Whole-doc — {MODEL_NAME}\")\n"
    "if VISION_AVAILABLE:\n"
    "    error_breakdown(errs_v, f\"Vision Batch — {MODEL_NAME}\")\n"
)

# ── Cell 13 — error detail tables ────────────────────────────────────────────
cells[13]["source"] = (
    "pd.set_option(\"display.max_colwidth\", 100)\n"
    "if not errs_b.empty:\n"
    "    print(\"=== Batch errors ===\")\n"
    "    display(errs_b[[\"sample\",\"page\",\"true\",\"pred\",\"text\"]])\n"
    "if WHOLEDOC_AVAILABLE and not errs_w.empty:\n"
    "    print(\"\\n=== Whole-doc errors ===\")\n"
    "    display(errs_w[[\"sample\",\"page\",\"true\",\"pred\",\"text\"]])\n"
    "if VISION_AVAILABLE and not errs_v.empty:\n"
    "    print(\"\\n=== Vision Batch errors ===\")\n"
    "    display(errs_v[[\"sample\",\"page\",\"true\",\"pred\",\"text\"]])\n"
)

# ── Cell 15 — PDF-direct comparison table (add vision) ───────────────────────
cells[15]["source"] = (
    "if PDF_AVAILABLE:\n"
    "    # ── All-strategy accuracy comparison ─────────────────────────────────\n"
    "    print(\"=== Strategy comparison ===\\n\")\n"
    "    rows_cmp = [\n"
    "        (\"Batch\",        df_b),\n"
    "        (\"Whole-doc\",    df_w),\n"
    "        (\"PDF-direct\",   df_p),\n"
    "    ]\n"
    "    if VISION_AVAILABLE:\n"
    "        rows_cmp.append((\"Vision Batch\", df_v))\n"
    "    hdr = f\"  {'Strategy':<14}  {'Blocks':>8}  {'Correct':>8}  {'Accuracy':>9}\"\n"
    "    print(hdr)\n"
    "    print(\"  \" + \"-\" * (len(hdr) - 2))\n"
    "    for label, df in rows_cmp:\n"
    "        if df is None or df.empty: continue\n"
    "        tc_ = int(df[\"correct\"].sum())\n"
    "        tn_ = int(df[\"total\"].sum())\n"
    "        print(f\"  {label:<14}  {tn_:>8}  {tc_:>8}  {tc_/tn_*100:>8.1f}%\")\n"
    "\n"
    "    # ── Block count per sample (pdfplumber vs pdf-direct) ────────────────\n"
    "    print(\"\\n=== Block count per sample ===\\n\")\n"
    "    hdr2 = f\"  {'Sample':<12}  {'Batch/WD':>9}  {'PDF-direct':>11}  {'Ratio':>7}\"\n"
    "    print(hdr2)\n"
    "    print(\"  \" + \"-\" * (len(hdr2) - 2))\n"
    "    for _, rb in df_b.iterrows():\n"
    "        s   = rb[\"sample\"]\n"
    "        nb_ = int(rb[\"total\"])\n"
    "        rp  = df_p[df_p[\"sample\"] == s]\n"
    "        np_ = int(rp[\"total\"].iloc[0]) if not rp.empty else 0\n"
    "        print(f\"  {s:<12}  {nb_:>9}  {np_:>11}  {np_/nb_*100:>6.0f}%\")\n"
    "    print(\"  \" + \"-\" * (len(hdr2) - 2))\n"
    "    print(f\"  {'TOTAL':<12}  {tn_b:>9}  {tn_p:>11}  {tn_p/tn_b*100:>6.0f}%\")\n"
    "else:\n"
    "    print(\"PDF-direct data not available — run: dmpbridge-pdf --model\", MODEL_DISPLAY)\n"
)

# ── Cell 16 — per-sample accuracy all strategies (add vision) ────────────────
cells[16]["source"] = (
    "if PDF_AVAILABLE:\n"
    "    samples_ordered = df_b[\"sample\"].tolist()\n"
    "    x = range(len(samples_ordered))\n"
    "\n"
    "    plot_strats = [\n"
    "        (\"Batch\",        df_b, COLOR_BATCH,  True),\n"
    "        (\"Whole-doc\",    df_w, COLOR_WHOLE,  WHOLEDOC_AVAILABLE),\n"
    "        (\"PDF-direct\",   df_p, COLOR_PDF,    True),\n"
    "        (\"Vision Batch\", df_v, COLOR_VISION, VISION_AVAILABLE),\n"
    "    ]\n"
    "    plot_strats = [(lbl, df, col) for lbl, df, col, flag in plot_strats if flag]\n"
    "    n_ps = len(plot_strats)\n"
    "    w    = 0.8 / n_ps\n"
    "\n"
    "    fig, ax = plt.subplots(figsize=(14, 5))\n"
    "    for i, (lbl, df, color) in enumerate(plot_strats):\n"
    "        offset = (i - (n_ps - 1) / 2) * w\n"
    "        acc = df.set_index(\"sample\").reindex(samples_ordered)[\"accuracy\"] * 100\n"
    "        bars = ax.bar([xi + offset for xi in x], acc, width=w,\n"
    "                      label=lbl, color=color, alpha=0.85, edgecolor=\"white\")\n"
    "        for bar, v in zip(bars, acc):\n"
    "            if not pd.isna(v):\n"
    "                ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,\n"
    "                        f\"{v:.0f}%\", ha=\"center\", va=\"bottom\", fontsize=7)\n"
    "\n"
    "    ax.set_xticks(list(x)); ax.set_xticklabels(samples_ordered, rotation=30)\n"
    "    ax.set_ylim(55, 118); ax.set_ylabel(\"Accuracy (%)\")\n"
    "    ax.set_title(f\"Per-sample accuracy — {MODEL_NAME} — all strategies\", pad=10)\n"
    "    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f\"{v:.0f}%\"))\n"
    "    ax.legend(framealpha=0.9); sns.despine(); plt.tight_layout(); plt.show()\n"
)

# ── Cell 17 — F1 for all 4 strategies (2x2 grid) ─────────────────────────────
cells[17]["source"] = (
    "if PDF_AVAILABLE:\n"
    "    mat_p, mat_pn = conf_to_df(conf_p)\n"
    "\n"
    "    # ── Confusion matrix — PDF-direct ────────────────────────────────────\n"
    "    fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n"
    "    for ax, mat, fmt, title in [\n"
    "        (axes[0], mat_p,  \"d\",   \"PDF-direct — raw counts\"),\n"
    "        (axes[1], mat_pn, \".0%\", \"PDF-direct — row-normalised recall\"),\n"
    "    ]:\n"
    "        sns.heatmap(mat, annot=True, fmt=fmt, cmap=CMAP_PDF, linewidths=0.6,\n"
    "                    linecolor=\"white\", ax=ax, cbar=False, annot_kws={\"size\": 11},\n"
    "                    vmin=(0 if fmt == \".0%\" else None), vmax=(1 if fmt == \".0%\" else None))\n"
    "        ax.set_title(title, pad=8, fontsize=11)\n"
    "        ax.set_xlabel(\"Predicted\", labelpad=6); ax.set_ylabel(\"True\", labelpad=6)\n"
    "    plt.suptitle(f\"Confusion matrix — {MODEL_NAME} — PDF-direct\", fontsize=13, y=1.02)\n"
    "    plt.tight_layout(); plt.show()\n"
    "\n"
    "    # ── F1 — all strategies (2x2 grid) ───────────────────────────────────\n"
    "    df_f1_b_ = compute_f1_rows(conf_b)\n"
    "    df_f1_w_ = compute_f1_rows(conf_w) if WHOLEDOC_AVAILABLE else None\n"
    "    df_f1_p  = compute_f1_rows(conf_p)\n"
    "    df_f1_v_ = compute_f1_rows(conf_v) if VISION_AVAILABLE   else None\n"
    "\n"
    "    all_f1 = [\n"
    "        (df_f1_b_, COLOR_BATCH,  f\"Batch — {MODEL_NAME}\"),\n"
    "        (df_f1_w_, COLOR_WHOLE,  f\"Whole-doc — {MODEL_NAME}\"),\n"
    "        (df_f1_p,  COLOR_PDF,    f\"PDF-direct — {MODEL_NAME}\"),\n"
    "        (df_f1_v_, COLOR_VISION, f\"Vision Batch — {MODEL_NAME}\"),\n"
    "    ]\n"
    "    all_f1 = [(df, col, title) for df, col, title in all_f1 if df is not None]\n"
    "\n"
    "    n_f = len(all_f1)\n"
    "    ncols = 2; nrows = (n_f + 1) // 2\n"
    "    fig, axes = plt.subplots(nrows, ncols, figsize=(16, 5.5 * nrows))\n"
    "    axes_flat = axes.flatten() if hasattr(axes, 'flatten') else [axes]\n"
    "\n"
    "    for ax, (df_f1, color, title) in zip(axes_flat, all_f1):\n"
    "        xi, bw = range(len(LABELS)), 0.26\n"
    "        ax.bar([i - bw for i in xi], df_f1[\"precision\"]*100, width=bw,\n"
    "               label=\"Precision\", color=color, alpha=0.5, edgecolor=\"white\")\n"
    "        ax.bar([i      for i in xi], df_f1[\"recall\"]*100,    width=bw,\n"
    "               label=\"Recall\",    color=color, alpha=0.75, edgecolor=\"white\")\n"
    "        bars = ax.bar([i + bw for i in xi], df_f1[\"f1\"]*100, width=bw,\n"
    "                      label=\"F1\", color=color, edgecolor=\"white\")\n"
    "        for bar, row in zip(bars, df_f1.itertuples()):\n"
    "            ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.8,\n"
    "                    f\"{row.f1*100:.0f}%\", ha=\"center\", va=\"bottom\",\n"
    "                    fontsize=9, fontweight=\"bold\", color=color)\n"
    "        ax.set_xticks(list(xi)); ax.set_xticklabels(SHORT, fontsize=10)\n"
    "        ax.set_ylim(0, 120); ax.set_ylabel(\"Score (%)\"); ax.set_title(title, pad=10)\n"
    "        ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f\"{v:.0f}%\"))\n"
    "        ax.legend(loc=\"upper right\", framealpha=0.9); sns.despine(ax=ax)\n"
    "\n"
    "    for ax in axes_flat[n_f:]:\n"
    "        ax.set_visible(False)\n"
    "\n"
    "    plt.suptitle(f\"Precision / Recall / F1 — {MODEL_NAME} — all strategies\", fontsize=13, y=1.02)\n"
    "    plt.tight_layout(); plt.show()\n"
    "\n"
    "    # ── F1 delta table: all strategies vs batch ───────────────────────────\n"
    "    comb = df_f1_b_.set_index(\"label\")[[\"f1\"]].rename(columns={\"f1\":\"batch\"})\n"
    "    if df_f1_w_ is not None:\n"
    "        comb[\"whole-doc\"]    = df_f1_w_.set_index(\"label\")[\"f1\"].values\n"
    "        comb[\"Δ whole\"]      = comb[\"whole-doc\"] - comb[\"batch\"]\n"
    "    comb[\"pdf-direct\"]       = df_f1_p.set_index(\"label\")[\"f1\"].values\n"
    "    comb[\"Δ pdf\"]            = comb[\"pdf-direct\"] - comb[\"batch\"]\n"
    "    if df_f1_v_ is not None:\n"
    "        comb[\"vision-batch\"] = df_f1_v_.set_index(\"label\")[\"f1\"].values\n"
    "        comb[\"Δ vision\"]     = comb[\"vision-batch\"] - comb[\"batch\"]\n"
    "    score_cols = [c for c in comb.columns if not c.startswith(\"Δ\")]\n"
    "    display(comb.style.format(\"{:.1%}\").background_gradient(subset=score_cols, cmap=\"Blues\"))\n"
)

nb["cells"] = cells
p.write_text(json.dumps(nb, ensure_ascii=False, indent=1), encoding="utf-8")
print(f"Done — {len(cells)} cells")
